version: 2

# Wollmilchsau GoReleaser config
# NOTE: Because this project uses CGo (v8go), cross-compilation is limited.
# It will build for the host system (usually Linux in GitHub Actions).

builds:
  - id: wollmilchsau
    main: .
    binary: wollmilchsau
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - README.de.md

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: wollmilchsau-packages
    package_name: wollmilchsau
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    vendor: Michael Lechner
    homepage: https://github.com/hmsoft0815/wollmilchsau
    maintainer: Michael Lechner <michael@mlcgo.eu>
    description: High-performance TypeScript execution engine for MCP.
    license: MIT
    formats:
      - deb
      - rpm
    builds:
      - wollmilchsau
    contents:
      - src: wollmilchsau
        dst: /usr/bin/wollmilchsau

snapshot:
  name_template: "{{ incpatch .Version }}-next"
