version: '3'

vars:
  BINARY: build/wollmilchsau

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the wollmilchsau binary
    cmds:
      - mkdir -p build
      - CGO_ENABLED=1 go build -trimpath -o {{.BINARY}} ./cmd/main.go
    sources:
      - "**/*.go"
      - go.mod
    generates:
      - "{{.BINARY}}"

  docker-build:
    desc: Build the Docker image
    cmds:
      - docker build -t wollmilchsau .

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  tidy:
    desc: Tidy go.mod
    cmds:
      - go mod tidy

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf build/
