version: '3'

vars:
  BINARY: build/wollmilchsau

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the wollmilchsau binary
    cmds:
      - mkdir -p build
      - CGO_ENABLED=1 go build -trimpath -o {{.BINARY}} ./cmd/main.go
    sources:
      - "**/*.go"
      - go.mod
    generates:
      - "{{.BINARY}}"

  docker-build:
    desc: Build the Docker image
    cmds:
      - docker build -t wollmilchsau .

  test:
    desc: Run all tests
    cmds:
      - go test ./...
      - task: test-mcp
      - task: test-mcp-extended

  test-mcp:
    desc: Run basic interaction tests using mcp-tester
    deps: [build]
    vars:
      MCP_TESTER: mcp-tester
    cmds:
      - "{{.MCP_TESTER}} test --command {{.BINARY}} --script tests/basic.mcp"
    preconditions:
      - sh: command -v {{.MCP_TESTER}}
        msg: "mcp-tester not found. Please install it first."

  test-mcp-extended:
    desc: Run extended interaction tests (multi-file) using mcp-tester
    deps: [build]
    vars:
      MCP_TESTER: mcp-tester
    cmds:
      - "{{.MCP_TESTER}} test --command {{.BINARY}} --script tests/extended.mcp"
    preconditions:
      - sh: command -v {{.MCP_TESTER}}
        msg: "mcp-tester not found."

  tidy:
    desc: Tidy go.mod
    cmds:
      - go mod tidy

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf build/
